# basic options
title: New-awesome blog 
author: Smart Guy
name: Evan Will
email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."
twitter-username: potus
github-username: evanwall

# Build settings
markdown: kramdown
theme: minima

